//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preferiti
    {
        public int Id { get; set; }
        public int id_prodotto { get; set; }
        public int id_utente { get; set; }
    }
}
