//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prodotti
    {
        public int Id { get; set; }
        public string nome_prodotto { get; set; }
        public double prezzo { get; set; }
    }
}
